import {
  ArrowRightLeft,
  BarChart2,
  Bot,
  Briefcase,
  CircleHelp,
  Cloud,
  Code,
  Cpu,
  EyeOff,
  FolderSync,
  Gamepad2,
  Globe,
  GraduationCap,
  HardDrive,
  Image,
  Landmark,
  Megaphone,
  MessageSquare,
  Music,
  Newspaper,
  Plane,
  Server,
  Settings,
  Share2,
  Shield,
  ShieldAlert,
  ShieldCheck,
  ShoppingBag,
  Skull,
  Tv,
  Users,
  Video,
  type LucideIcon,
} from "lucide-react";

export const categoryIcons: Record<string, LucideIcon> = {
  finance: Landmark,
  travel: Plane,
  news: Newspaper,
  education: GraduationCap,
  productivity: Briefcase,
  web: Globe,
  streaming: Tv,
  video: Video,
  audio: Music,
  music: Music,
  shopping: ShoppingBag,
  cdn: Server,
  iot: Cpu,
  adult: EyeOff,
  social: Users,
  development: Code,
  technology: Code,
  ai: Bot,
  cloud: Cloud,
  storage: HardDrive,
  media: Image,
  gaming: Gamepad2,
  p2p: Share2,
  vpn: Shield,
  proxy: ArrowRightLeft,
  network: Globe,
  encrypted_dns: ShieldCheck,
  file_transfer: FolderSync,
  communication: MessageSquare,
  system: Settings,
  advertising: Megaphone,
  analytics: BarChart2,
  malware: Skull,
  security: ShieldAlert,
  unknown: CircleHelp,
};

export function getCategoryIcon(categoryId?: string | null): LucideIcon {
  if (!categoryId) return CircleHelp;
  const normalized = categoryId
    .toLowerCase()
    .trim()
    .replace(/[-\s]+/g, "_");
  return categoryIcons[normalized] ?? CircleHelp;
}
