"use client";

import type { SimpleIcon } from "simple-icons";
import {
  si4chan,
  si500px,
  si9gag,
  siActualbudget,
  siAdminer,
  siActivision,
  siAlibabadotcom,
  siAliexpress,
  siAnthropic,
  siApple,
  siAudiobookshelf,
  siAutomattic,
  siBaidu,
  siBattledotnet,
  siBilibili,
  siBluesky,
  siBox,
  siBytedance,
  siCalibreweb,
  siCdprojekt,
  siCloudflare,
  siClubhouse,
  siCrunchyroll,
  siDailymotion,
  siDiscord,
  siDeluge,
  siDouban,
  siDropbox,
  siDuplicati,
  siEa,
  siEbay,
  siEpicgames,
  siFacebook,
  siFifa,
  siFreshrss,
  siFrigate,
  siGitea,
  siGithub,
  siGitlab,
  siGogdotcom,
  siGoogle,
  siGoogleplay,
  siGrafana,
  siHbo,
  siHomeassistant,
  siHomebridge,
  siIheartradio,
  siImgur,
  siInstagram,
  siImmich,
  siJellyfin,
  siJenkins,
  siKakaotalk,
  siKik,
  siLeagueoflegends,
  siLine,
  siLangflow,
  siMaildotru,
  siMastodon,
  siMeituan,
  siMercadopago,
  siMeta,
  siNbc,
  siNebula,
  siNetflix,
  siNetdata,
  siNextcloud,
  siNginxproxymanager,
  siNodered,
  siNvidia,
  siOdnoklassniki,
  siOdysee,
  siOnlyfans,
  siObsidian,
  siOpenhab,
  siOpenai,
  siOrigin,
  siParamountplus,
  siPerplexity,
  siPinterest,
  siPihole,
  siPlaystation,
  siPlex,
  siPortainer,
  siQbittorrent,
  siQq,
  siRakuten,
  siReddit,
  siRiotgames,
  siRoblox,
  siRockstargames,
  siSalesforce,
  siSamsung,
  siShopee,
  siSignal,
  siSinaweibo,
  siSlack,
  siSnapchat,
  siSony,
  siSoundcloud,
  siSonarr,
  siSpotify,
  siSquare,
  siSteam,
  siSyncthing,
  siTelefonica,
  siTelegram,
  siTidal,
  siTiktok,
  siTumblr,
  siTwitch,
  siUbisoft,
  siValve,
  siVaultwarden,
  siViber,
  siVimeo,
  siVk,
  siWarnerbros,
  siWechat,
  siWhatsapp,
  siX,
  siXiaohongshu,
  siYoutube,
  siZhihu,
  siZoom,
} from "simple-icons";

import { cn } from "@/lib/utils";

const icons: Record<string, SimpleIcon> = {
  "4chan": si4chan,
  "500px": si500px,
  "9gag": si9gag,
  actualbudget: siActualbudget,
  adminer: siAdminer,
  activision: siActivision,
  alibabadotcom: siAlibabadotcom,
  aliexpress: siAliexpress,
  anthropic: siAnthropic,
  apple: siApple,
  audiobookshelf: siAudiobookshelf,
  automattic: siAutomattic,
  baidu: siBaidu,
  battledotnet: siBattledotnet,
  bilibili: siBilibili,
  bluesky: siBluesky,
  box: siBox,
  bytedance: siBytedance,
  calibreweb: siCalibreweb,
  cdprojekt: siCdprojekt,
  cloudflare: siCloudflare,
  clubhouse: siClubhouse,
  crunchyroll: siCrunchyroll,
  dailymotion: siDailymotion,
  discord: siDiscord,
  deluge: siDeluge,
  douban: siDouban,
  dropbox: siDropbox,
  duplicati: siDuplicati,
  ea: siEa,
  ebay: siEbay,
  epicgames: siEpicgames,
  facebook: siFacebook,
  fifa: siFifa,
  freshrss: siFreshrss,
  frigate: siFrigate,
  gitea: siGitea,
  github: siGithub,
  gitlab: siGitlab,
  gogdotcom: siGogdotcom,
  google: siGoogle,
  googleplay: siGoogleplay,
  grafana: siGrafana,
  hbo: siHbo,
  homeassistant: siHomeassistant,
  homebridge: siHomebridge,
  iheartradio: siIheartradio,
  imgur: siImgur,
  instagram: siInstagram,
  immich: siImmich,
  jellyfin: siJellyfin,
  jenkins: siJenkins,
  kakaotalk: siKakaotalk,
  kik: siKik,
  leagueoflegends: siLeagueoflegends,
  line: siLine,
  langflow: siLangflow,
  maildotru: siMaildotru,
  mastodon: siMastodon,
  meituan: siMeituan,
  mercadopago: siMercadopago,
  meta: siMeta,
  nbc: siNbc,
  nebula: siNebula,
  netflix: siNetflix,
  netdata: siNetdata,
  nextcloud: siNextcloud,
  nginxproxymanager: siNginxproxymanager,
  nodered: siNodered,
  nvidia: siNvidia,
  odnoklassniki: siOdnoklassniki,
  odysee: siOdysee,
  onlyfans: siOnlyfans,
  obsidian: siObsidian,
  openhab: siOpenhab,
  openai: siOpenai,
  origin: siOrigin,
  paramountplus: siParamountplus,
  perplexity: siPerplexity,
  pinterest: siPinterest,
  pihole: siPihole,
  playstation: siPlaystation,
  plex: siPlex,
  portainer: siPortainer,
  qbittorrent: siQbittorrent,
  qq: siQq,
  rakuten: siRakuten,
  reddit: siReddit,
  riotgames: siRiotgames,
  roblox: siRoblox,
  rockstargames: siRockstargames,
  salesforce: siSalesforce,
  samsung: siSamsung,
  shopee: siShopee,
  signal: siSignal,
  sinaweibo: siSinaweibo,
  slack: siSlack,
  snapchat: siSnapchat,
  sony: siSony,
  soundcloud: siSoundcloud,
  sonarr: siSonarr,
  spotify: siSpotify,
  square: siSquare,
  steam: siSteam,
  syncthing: siSyncthing,
  telefonica: siTelefonica,
  telegram: siTelegram,
  tidal: siTidal,
  tiktok: siTiktok,
  tumblr: siTumblr,
  twitch: siTwitch,
  twitter: siX,
  ubisoft: siUbisoft,
  valve: siValve,
  vaultwarden: siVaultwarden,
  viber: siViber,
  vimeo: siVimeo,
  vk: siVk,
  warnerbros: siWarnerbros,
  wechat: siWechat,
  whatsapp: siWhatsapp,
  x: siX,
  xiaohongshu: siXiaohongshu,
  youtube: siYoutube,
  zhihu: siZhihu,
  zoom: siZoom,
};

export function hasSimpleBrandIcon(iconKey?: string | null) {
  return Boolean(iconKey && icons[iconKey]);
}

export function SimpleBrandIcon({
  iconKey,
  className,
}: {
  iconKey?: string | null;
  className?: string;
}) {
  const icon = iconKey ? icons[iconKey] : undefined;
  if (!icon) return null;
  return (
    <svg
      viewBox="0 0 24 24"
      aria-hidden="true"
      className={cn("size-4", className)}
      role="img"
    >
      <path d={icon.path} fill={`#${icon.hex}`} />
    </svg>
  );
}
