"use client";

import type { SimpleIcon } from "simple-icons";
import {
  si1and1,
  si1password,
  si2k,
  si4chan,
  si500px,
  si9gag,
  siAccuweather,
  siActivision,
  siActualbudget,
  siAdblockplus,
  siAdguard,
  siAdminer,
  siAirasia,
  siAirbnb,
  siAircall,
  siAkamai,
  siAlibabacloud,
  siAlibabadotcom,
  siAliexpress,
  siAlipay,
  siAlltrails,
  siAmeba,
  siAmericanairlines,
  siAnthropic,
  siAnydesk,
  siApache,
  siApple,
  siApplemusic,
  siAppletv,
  siAppstore,
  siAsana,
  siAsus,
  siAtandt,
  siAtlassian,
  siAudacity,
  siAudible,
  siAudiobookshelf,
  siAudiomack,
  siAutomattic,
  siAvast,
  siAvira,
  siAvm,
  siBackblaze,
  siBadoo,
  siBaidu,
  siBandlab,
  siBattledotnet,
  siBereal,
  siBetfair,
  siBilibili,
  siBinance,
  siBitcomet,
  siBitdefender,
  siBittorrent,
  siBlackberry,
  siBlogger,
  siBluesky,
  siBohemiainteractive,
  siBookingdotcom,
  siBox,
  siBritishairways,
  siBungie,
  siBytedance,
  siCalibreweb,
  siCanva,
  siCanonical,
  siCastbox,
  siCbs,
  siCdprojekt,
  siChannel4,
  siChase,
  siChessdotcom,
  siCircle,
  siCisco,
  siCloudflare,
  siClubhouse,
  siCnn,
  siCpanel,
  siCrunchyroll,
  siCsdn,
  siCursor,
  siDailymotion,
  siDazn,
  siDebian,
  siDeepl,
  siDeliveroo,
  siDeluge,
  siDeutschetelekom,
  siDiscord,
  siDji,
  siDocker,
  siDoordash,
  siDota2,
  siDouban,
  siDropbox,
  siDuckduckgo,
  siDuolingo,
  siDuplicati,
  siEa,
  siEbay,
  siEdx,
  siEgnyte,
  siElevenlabs,
  siEpicgames,
  siEtsy,
  siEvernote,
  siExpedia,
  siExpo,
  siExpressvpn,
  siFacebook,
  siFastly,
  siFedex,
  siFeedly,
  siFifa,
  siFigma,
  siFilezilla,
  siFirefox,
  siFitbit,
  siFizz,
  siFlickr,
  siFlipboard,
  siFoodpanda,
  siFortnite,
  siFoursquare,
  siFreenet,
  siFreshrss,
  siFrigate,
  siFritz,
  siFubo,
  siGameloft,
  siGcore,
  siGarmin,
  siGeocaching,
  siGiphy,
  siGitea,
  siGithub,
  siGitlab,
  siGmx,
  siGodaddy,
  siGogdotcom,
  siGoodreads,
  siGoogle,
  siGoogleanalytics,
  siGooglecalendar,
  siGooglechat,
  siGoogledocs,
  siGoogleearth,
  siGooglecloud,
  siGooglenews,
  siGoogleplay,
  siGoogletasks,
  siGotomeeting,
  siGrab,
  siGrafana,
  siGroupon,
  siGumtree,
  siHandm,
  siHandshake,
  siHbo,
  siHbomax,
  siHevy,
  siHilton,
  siHomeassistant,
  siHomebridge,
  siHootsuite,
  siHotelsdotcom,
  siHuawei,
  siHuggingface,
  siIcloud,
  siIheartradio,
  siIkea,
  siIledefrancemobilites,
  siImdb,
  siImgur,
  siImmich,
  siIndeed,
  siInsta360,
  siInstagram,
  siInternetarchive,
  siJbl,
  siJellyfin,
  siJenkins,
  siKahoot,
  siKakao,
  siKakaotalk,
  siKaspersky,
  siKick,
  siKik,
  siKlarna,
  siKlook,
  siKodi,
  siKongregate,
  siLangflow,
  siLastdotfm,
  siLastpass,
  siLeagueoflegends,
  siLetsencrypt,
  siLetterboxd,
  siLg,
  siLine,
  siLivejournal,
  siLogmein,
  siLumen,
  siLyft,
  siMailchimp,
  siMaildotcom,
  siMaildotru,
  siMariadb,
  siMarriott,
  siMastodon,
  siMax,
  siMcafee,
  siMcdonalds,
  siMediafire,
  siMedium,
  siMeetup,
  siMega,
  siMeituan,
  siMendeley,
  siMercadopago,
  siMessenger,
  siMeta,
  siMiro,
  siMixpanel,
  siMlb,
  siMongodb,
  siMonica,
  siMozilla,
  siMullvad,
  siMumble,
  siMusescore,
  siMyspace,
  siNapster,
  siNaver,
  siNba,
  siNbc,
  siNebula,
  siNetdata,
  siNetflix,
  siNexon,
  siNextcloud,
  siNextdoor,
  siNginxproxymanager,
  siNgrok,
  siNhl,
  siNiconico,
  siNike,
  siNodered,
  siNordvpn,
  siNorton,
  siNotion,
  siNow,
  siNvidia,
  siObsidian,
  siObsstudio,
  siOdnoklassniki,
  siOdysee,
  siOkcupid,
  siOnlyfans,
  siOpenai,
  siOpenhab,
  siOpenvpn,
  siOpera,
  siOrange,
  siOrigin,
  siPandora,
  siParamountplus,
  siPaypal,
  siPerplexity,
  siPhotobucket,
  siPicsart,
  siPihole,
  siPinterest,
  siPlaystation,
  siPlex,
  siPlurk,
  siPoe,
  siPortainer,
  siPostgresql,
  siPostmates,
  siProton,
  siProtonvpn,
  siQbittorrent,
  siQq,
  siQuicktime,
  siQuizlet,
  siQuora,
  siRakuten,
  siReddit,
  siRenren,
  siReplit,
  siRevolut,
  siRing,
  siRiotgames,
  siRobinhood,
  siRoblox,
  siRockstargames,
  siRoku,
  siRtl,
  siRyanair,
  siSalesforce,
  siSamsung,
  siSap,
  siScribd,
  siSega,
  siShazam,
  siShopee,
  siShopify,
  siSignal,
  siSinaweibo,
  siSketchup,
  siSlack,
  siSlideshare,
  siSmartthings,
  siSmugmug,
  siSnapchat,
  siSoftpedia,
  siSogou,
  siSonarr,
  siSonos,
  siSony,
  siSoundcloud,
  siSpacex,
  siSpeedtest,
  siSpond,
  siSpotify,
  siSquare,
  siSquareenix,
  siStarbucks,
  siSteam,
  siStrava,
  siSubstack,
  siSubversion,
  siSuno,
  siSurfshark,
  siSway,
  siSymantec,
  siSyncthing,
  siTabelog,
  siTailscale,
  siTaobao,
  siTarget,
  siTeamspeak,
  siTeamviewer,
  siTed,
  siTelefonica,
  siTelegram,
  siTermius,
  siTheguardian,
  siThestorygraph,
  siThewashingtonpost,
  siTheweatherchannel,
  siThreads,
  siThreema,
  siTicketmaster,
  siTicktick,
  siTidal,
  siTiktok,
  siTile,
  siTinder,
  siTradingview,
  siTransmission,
  siTrello,
  siTrendmicro,
  siTrimble,
  siTripdotcom,
  siTrivago,
  siTubi,
  siTumblr,
  siTunein,
  siTwitch,
  siUber,
  siUbereats,
  siUbiquiti,
  siUbisoft,
  siUbuntu,
  siUnderarmour,
  siUnitedairlines,
  siUps,
  siUtorrent,
  siV0,
  siValve,
  siVaultwarden,
  siVercel,
  siViadeo,
  siViaplay,
  siViber,
  siVimeo,
  siVinted,
  siVk,
  siVmware,
  siWarnerbros,
  siWattpad,
  siWaze,
  siWebdotde,
  siWebex,
  siWebmin,
  siWechat,
  siWeread,
  siWesterndigital,
  siWetransfer,
  siWhatsapp,
  siWikipedia,
  siWinamp,
  siWise,
  siWish,
  siWordpress,
  siX,
  siXiaohongshu,
  siXiaomi,
  siXing,
  siYelp,
  siYoutube,
  siYoutubekids,
  siYr,
  siZara,
  siZendesk,
  siZerotier,
  siZhihu,
  siZillow,
  siZoom,
} from "simple-icons";

import { cn } from "@/lib/utils";

const icons: Record<string, SimpleIcon> = {
  "1and1": si1and1,
  "1password": si1password,
  "2k": si2k,
  "4chan": si4chan,
  "500px": si500px,
  "9gag": si9gag,
  accuweather: siAccuweather,
  activision: siActivision,
  actualbudget: siActualbudget,
  adblockplus: siAdblockplus,
  adguard: siAdguard,
  adminer: siAdminer,
  airasia: siAirasia,
  airbnb: siAirbnb,
  aircall: siAircall,
  akamai: siAkamai,
  alibabacloud: siAlibabacloud,
  alibabadotcom: siAlibabadotcom,
  aliexpress: siAliexpress,
  alipay: siAlipay,
  alltrails: siAlltrails,
  ameba: siAmeba,
  americanairlines: siAmericanairlines,
  anthropic: siAnthropic,
  anydesk: siAnydesk,
  apache: siApache,
  apple: siApple,
  applemusic: siApplemusic,
  appletv: siAppletv,
  appstore: siAppstore,
  asana: siAsana,
  asus: siAsus,
  atandt: siAtandt,
  atlassian: siAtlassian,
  audacity: siAudacity,
  audible: siAudible,
  audiobookshelf: siAudiobookshelf,
  audiomack: siAudiomack,
  automattic: siAutomattic,
  avast: siAvast,
  avira: siAvira,
  avm: siAvm,
  backblaze: siBackblaze,
  badoo: siBadoo,
  baidu: siBaidu,
  bandlab: siBandlab,
  battledotnet: siBattledotnet,
  bereal: siBereal,
  betfair: siBetfair,
  bilibili: siBilibili,
  binance: siBinance,
  bitcomet: siBitcomet,
  bitdefender: siBitdefender,
  bittorrent: siBittorrent,
  blackberry: siBlackberry,
  blogger: siBlogger,
  bluesky: siBluesky,
  bohemiainteractive: siBohemiainteractive,
  bookingdotcom: siBookingdotcom,
  box: siBox,
  britishairways: siBritishairways,
  bungie: siBungie,
  bytedance: siBytedance,
  calibreweb: siCalibreweb,
  canva: siCanva,
  canonical: siCanonical,
  castbox: siCastbox,
  cbs: siCbs,
  cdprojekt: siCdprojekt,
  channel4: siChannel4,
  chase: siChase,
  chessdotcom: siChessdotcom,
  circle: siCircle,
  cisco: siCisco,
  cloudflare: siCloudflare,
  clubhouse: siClubhouse,
  cnn: siCnn,
  cpanel: siCpanel,
  crunchyroll: siCrunchyroll,
  csdn: siCsdn,
  cursor: siCursor,
  dailymotion: siDailymotion,
  dazn: siDazn,
  debian: siDebian,
  deepl: siDeepl,
  deliveroo: siDeliveroo,
  deluge: siDeluge,
  deutschetelekom: siDeutschetelekom,
  discord: siDiscord,
  dji: siDji,
  docker: siDocker,
  doordash: siDoordash,
  dota2: siDota2,
  douban: siDouban,
  dropbox: siDropbox,
  duckduckgo: siDuckduckgo,
  duolingo: siDuolingo,
  duplicati: siDuplicati,
  ea: siEa,
  ebay: siEbay,
  edx: siEdx,
  egnyte: siEgnyte,
  elevenlabs: siElevenlabs,
  epicgames: siEpicgames,
  etsy: siEtsy,
  evernote: siEvernote,
  expedia: siExpedia,
  expo: siExpo,
  expressvpn: siExpressvpn,
  facebook: siFacebook,
  fastly: siFastly,
  fedex: siFedex,
  feedly: siFeedly,
  fifa: siFifa,
  figma: siFigma,
  filezilla: siFilezilla,
  firefox: siFirefox,
  fitbit: siFitbit,
  fizz: siFizz,
  flickr: siFlickr,
  flipboard: siFlipboard,
  foodpanda: siFoodpanda,
  fortnite: siFortnite,
  foursquare: siFoursquare,
  freenet: siFreenet,
  freshrss: siFreshrss,
  frigate: siFrigate,
  fritz: siFritz,
  fubo: siFubo,
  gameloft: siGameloft,
  gcore: siGcore,
  garmin: siGarmin,
  geocaching: siGeocaching,
  giphy: siGiphy,
  gitea: siGitea,
  github: siGithub,
  gitlab: siGitlab,
  gmx: siGmx,
  godaddy: siGodaddy,
  gogdotcom: siGogdotcom,
  goodreads: siGoodreads,
  google: siGoogle,
  googleanalytics: siGoogleanalytics,
  googlecalendar: siGooglecalendar,
  googlechat: siGooglechat,
  googledocs: siGoogledocs,
  googleearth: siGoogleearth,
  googlecloud: siGooglecloud,
  googlenews: siGooglenews,
  googleplay: siGoogleplay,
  googletasks: siGoogletasks,
  gotomeeting: siGotomeeting,
  grab: siGrab,
  grafana: siGrafana,
  groupon: siGroupon,
  gumtree: siGumtree,
  handm: siHandm,
  handshake: siHandshake,
  hbo: siHbo,
  hbomax: siHbomax,
  hevy: siHevy,
  hilton: siHilton,
  homeassistant: siHomeassistant,
  homebridge: siHomebridge,
  hootsuite: siHootsuite,
  hotelsdotcom: siHotelsdotcom,
  huawei: siHuawei,
  huggingface: siHuggingface,
  icloud: siIcloud,
  iheartradio: siIheartradio,
  ikea: siIkea,
  iledefrancemobilites: siIledefrancemobilites,
  imdb: siImdb,
  imgur: siImgur,
  immich: siImmich,
  indeed: siIndeed,
  insta360: siInsta360,
  instagram: siInstagram,
  internetarchive: siInternetarchive,
  jbl: siJbl,
  jellyfin: siJellyfin,
  jenkins: siJenkins,
  kahoot: siKahoot,
  kakao: siKakao,
  kakaotalk: siKakaotalk,
  kaspersky: siKaspersky,
  kick: siKick,
  kik: siKik,
  klarna: siKlarna,
  klook: siKlook,
  kodi: siKodi,
  kongregate: siKongregate,
  langflow: siLangflow,
  lastdotfm: siLastdotfm,
  lastpass: siLastpass,
  leagueoflegends: siLeagueoflegends,
  letsencrypt: siLetsencrypt,
  letterboxd: siLetterboxd,
  lg: siLg,
  line: siLine,
  livejournal: siLivejournal,
  logmein: siLogmein,
  lumen: siLumen,
  lyft: siLyft,
  mailchimp: siMailchimp,
  maildotcom: siMaildotcom,
  maildotru: siMaildotru,
  mariadb: siMariadb,
  marriott: siMarriott,
  mastodon: siMastodon,
  max: siMax,
  mcafee: siMcafee,
  mcdonalds: siMcdonalds,
  mediafire: siMediafire,
  medium: siMedium,
  meetup: siMeetup,
  mega: siMega,
  meituan: siMeituan,
  mendeley: siMendeley,
  mercadopago: siMercadopago,
  messenger: siMessenger,
  meta: siMeta,
  miro: siMiro,
  mixpanel: siMixpanel,
  mlb: siMlb,
  mongodb: siMongodb,
  monica: siMonica,
  mozilla: siMozilla,
  mullvad: siMullvad,
  mumble: siMumble,
  musescore: siMusescore,
  myspace: siMyspace,
  napster: siNapster,
  naver: siNaver,
  nba: siNba,
  nbc: siNbc,
  nebula: siNebula,
  netdata: siNetdata,
  netflix: siNetflix,
  nexon: siNexon,
  nextcloud: siNextcloud,
  nextdoor: siNextdoor,
  nginxproxymanager: siNginxproxymanager,
  ngrok: siNgrok,
  nhl: siNhl,
  niconico: siNiconico,
  nike: siNike,
  nodered: siNodered,
  nordvpn: siNordvpn,
  norton: siNorton,
  notion: siNotion,
  now: siNow,
  nvidia: siNvidia,
  obsidian: siObsidian,
  obsstudio: siObsstudio,
  odnoklassniki: siOdnoklassniki,
  odysee: siOdysee,
  okcupid: siOkcupid,
  onlyfans: siOnlyfans,
  openai: siOpenai,
  openhab: siOpenhab,
  openvpn: siOpenvpn,
  opera: siOpera,
  orange: siOrange,
  origin: siOrigin,
  pandora: siPandora,
  paramountplus: siParamountplus,
  paypal: siPaypal,
  perplexity: siPerplexity,
  photobucket: siPhotobucket,
  picsart: siPicsart,
  pihole: siPihole,
  pinterest: siPinterest,
  playstation: siPlaystation,
  plex: siPlex,
  plurk: siPlurk,
  poe: siPoe,
  portainer: siPortainer,
  postgresql: siPostgresql,
  postmates: siPostmates,
  proton: siProton,
  protonvpn: siProtonvpn,
  qbittorrent: siQbittorrent,
  qq: siQq,
  quicktime: siQuicktime,
  quizlet: siQuizlet,
  quora: siQuora,
  rakuten: siRakuten,
  reddit: siReddit,
  renren: siRenren,
  replit: siReplit,
  revolut: siRevolut,
  ring: siRing,
  riotgames: siRiotgames,
  robinhood: siRobinhood,
  roblox: siRoblox,
  rockstargames: siRockstargames,
  roku: siRoku,
  rtl: siRtl,
  ryanair: siRyanair,
  salesforce: siSalesforce,
  samsung: siSamsung,
  sap: siSap,
  scribd: siScribd,
  sega: siSega,
  shazam: siShazam,
  shopee: siShopee,
  shopify: siShopify,
  signal: siSignal,
  sinaweibo: siSinaweibo,
  sketchup: siSketchup,
  slack: siSlack,
  slideshare: siSlideshare,
  smartthings: siSmartthings,
  smugmug: siSmugmug,
  snapchat: siSnapchat,
  softpedia: siSoftpedia,
  sogou: siSogou,
  sonarr: siSonarr,
  sonos: siSonos,
  sony: siSony,
  soundcloud: siSoundcloud,
  spacex: siSpacex,
  speedtest: siSpeedtest,
  spond: siSpond,
  spotify: siSpotify,
  square: siSquare,
  squareenix: siSquareenix,
  starbucks: siStarbucks,
  steam: siSteam,
  strava: siStrava,
  substack: siSubstack,
  subversion: siSubversion,
  suno: siSuno,
  surfshark: siSurfshark,
  sway: siSway,
  symantec: siSymantec,
  syncthing: siSyncthing,
  tabelog: siTabelog,
  tailscale: siTailscale,
  taobao: siTaobao,
  target: siTarget,
  teamspeak: siTeamspeak,
  teamviewer: siTeamviewer,
  ted: siTed,
  telefonica: siTelefonica,
  telegram: siTelegram,
  termius: siTermius,
  theguardian: siTheguardian,
  thestorygraph: siThestorygraph,
  thewashingtonpost: siThewashingtonpost,
  theweatherchannel: siTheweatherchannel,
  threads: siThreads,
  threema: siThreema,
  ticketmaster: siTicketmaster,
  ticktick: siTicktick,
  tidal: siTidal,
  tiktok: siTiktok,
  tile: siTile,
  tinder: siTinder,
  tradingview: siTradingview,
  transmission: siTransmission,
  trello: siTrello,
  trendmicro: siTrendmicro,
  trimble: siTrimble,
  tripdotcom: siTripdotcom,
  trivago: siTrivago,
  tubi: siTubi,
  tumblr: siTumblr,
  tunein: siTunein,
  twitch: siTwitch,
  twitter: siX,
  uber: siUber,
  ubereats: siUbereats,
  ubiquiti: siUbiquiti,
  ubisoft: siUbisoft,
  ubuntu: siUbuntu,
  underarmour: siUnderarmour,
  unitedairlines: siUnitedairlines,
  ups: siUps,
  utorrent: siUtorrent,
  v0: siV0,
  valve: siValve,
  vaultwarden: siVaultwarden,
  vercel: siVercel,
  viadeo: siViadeo,
  viaplay: siViaplay,
  viber: siViber,
  vimeo: siVimeo,
  vinted: siVinted,
  vk: siVk,
  vmware: siVmware,
  warnerbros: siWarnerbros,
  wattpad: siWattpad,
  waze: siWaze,
  webdotde: siWebdotde,
  webex: siWebex,
  webmin: siWebmin,
  wechat: siWechat,
  weread: siWeread,
  westerndigital: siWesterndigital,
  wetransfer: siWetransfer,
  whatsapp: siWhatsapp,
  wikipedia: siWikipedia,
  winamp: siWinamp,
  wise: siWise,
  wish: siWish,
  wordpress: siWordpress,
  x: siX,
  xiaohongshu: siXiaohongshu,
  xiaomi: siXiaomi,
  xing: siXing,
  yelp: siYelp,
  youtube: siYoutube,
  youtubekids: siYoutubekids,
  yr: siYr,
  zara: siZara,
  zendesk: siZendesk,
  zerotier: siZerotier,
  zhihu: siZhihu,
  zillow: siZillow,
  zoom: siZoom,
};

export function hasSimpleBrandIcon(iconKey?: string | null) {
  return Boolean(iconKey && icons[iconKey]);
}

export function SimpleBrandIcon({
  iconKey,
  className,
}: {
  iconKey?: string | null;
  className?: string;
}) {
  const icon = iconKey ? icons[iconKey] : undefined;
  if (!icon) return null;
  return (
    <svg
      viewBox="0 0 24 24"
      aria-hidden="true"
      className={cn("size-4", className)}
      role="img"
    >
      <path d={icon.path} fill={`#${icon.hex}`} />
    </svg>
  );
}
